### ISSUE TITLE
Using Vuex to persist authenticated user 

### ISSUE THREAD

**Issue by upwebdesign** [jnt0r/vue-auth0-plugin#103]
@jnt0r Ive run into another snag and I could be just overlooking something, but when I authenticate and am returned back to the app, I am logged in just fine. Once I reload the app my authentication is removed and I have to re authenticate. What are your thoughts on this and how would you recommend persisting authentication?

**Comment by jnt0r** [comment]
Normally there should be set a token by auth0 and when authenticated and reloading the page you should still be logged in. But it can take some time to check if the authentication is ok. That's what the loading property is for.
In my local example, I cannot reproduce this.

Do you redirect manually if the user is not logged in?
Does it happen on every route you have?
Or could you provide some more context of what you're doing on the page you were logged out after refresh.

**Comment by upwebdesign** [comment]
@jnt0r thanks for your response. I will respond later today when I have more context.

**Comment by upwebdesign** [comment]
@jnt0r here is an update. After authenticating with Auth0, upon reloading the page I am getting this console error.

`Failed to load resource: the server responded with a status of 400 ()`

This is the request that is giving the 400 response:

`https://***.us.auth0.com/authorize?client_id=***&redirect_uri=***&scope=openid%20profile%20email&response_type=code&response_mode=web_message&state=***&nonce=***&code_challenge=***&code_challenge_method=S256&prompt=none&auth0Client=***
`

I've verified the domain, client_id and redirect_uri are all correct. I am continuing to debug this.

**Comment by upwebdesign** [comment]
@jnt0r the difference I see so far is initial login uses the `query` response mode where reloading (already authenticated) uses `web_message` response mode.

**Comment by upwebdesign** [comment]
@jnt0r I figured it out. Finally I realized that there is a logs section in the Auth0 portal. After reviewing the logs, I found a message stating `The specified redirect_uri 'https://domain.test' does not have a registered origin.`. My domain was in the `Allowed Web Origins` section but as `https://*domain.test`. Removing the `*` solved this issue. Thanks for hanging in there with me through this process. You can close this issue at your convenience.

**Comment by jnt0r** [comment]
Okay, interesting reason of the problem. But nice, that you figured it out 👍🏽
