### ISSUE TITLE
Upon login, the code is visible in the address bar

### ISSUE THREAD

**Issue by upwebdesign** [jnt0r/vue-auth0-plugin#121]
@jnt0r I have been noticing that the code, after authentication, is still visible in the address bar after the user has been logged in. I assume this is in part the responsibility of the guard that us used. So, for example, this is what I see after being authenticated:

```
http://localhost:8080/?code={code would be here}#/
```

It then persists through all the routing throughout the app. I usually have a potential solution to these types of issues, but I just don't have one at this time. I will continue to dig, but if you know why this behavior exists and how to prevent it, that would be great!

Thanks as always!

**Comment by upwebdesign** [comment]
@jnt0r I think I found the issue. At one point we were using `createWebHashHistory()` with the router config, decided not use that option and chose `createWebHistory()` instead. The issue popped its ugly head with `createWebHashHistory()`. Still an issue, but who uses hashes in the URL's anymore? Ha

**Comment by jnt0r** [comment]
Hi @upwebdesign, thanks for mentioning this. I just tried it out and can confirm this. I'm going to research a little bit and try to fix it.
