### ISSUE TITLE
Allowing for guest routes

### ISSUE THREAD

**Issue by upwebdesign** [jnt0r/vue-auth0-plugin#132]
@jnt0r one thing I have been struggling with is how to implement guest access to specific routes. Please find below what I have come to use up to this point. Let me know if you have a better solution to implement guest access to certain pages. It would be convenient if your AuthenticationGuard would support this out of the gate. The real issue is that the guarded page shows briefly before being redirected to Auth0 for authentication.

```ts
router.beforeEach((to, from, next) => {
  new Promise<boolean>((resolve) => {
    if (to.meta.guest) {
      resolve(true);
      return true;
    }
    AuthenticationGuard(to, from).then((ok) => {
      resolve(ok);
    });
  }).then((ok) => {
    ok ? next() : next(false);
  });
});
```

Let me know if I am being too pushy or if you expect more out of me with these findings.

**Comment by jnt0r** [comment]
I also noticed that the page sometimes flickers up before getting redirected. Didn't yet thought about how to solve it.
Will think about this when I have a minute :) Thanks for mentioning it.

**Comment by jnt0r** [comment]
Hey @upwebdesign, sorry for not answering for quite long. Do you still see this as a problem? I just tried it out, and I don't see the protected site flickering anymore.
I would not like to implement a guest feature in the AuthenticationGuard as it is used to protect the private pages, that should only be visible to authenticated users. So I think your way of implementing guest access to protected routes is a good way to go.

**Comment by upwebdesign** [comment]
@jnt0r Im no long on the project that was/is using your package. Thanks for reaching out!
