### ISSUE TITLE
Accessing plugin state using an export

### ISSUE THREAD

**Issue by upwebdesign** [jnt0r/vue-auth0-plugin#139]
@jnt0r is it possible to export the plugin state along with the AuthenticationGuard? I am attempting to determine if the user is authenticated in the beforeEnter method of vue router. I am struggling to find a way to see if the user is actually authenticated before loading the component.

I not only want to protect pages with authentication, which is what the AuthenticationGuard is doing, but I also dont want people to access, for example, `/login` if they are logged in. If they do, I want to send them to a different view, `/home` in this case.

I cannot get access to the Vue instance in beforeEnter method from what I read.

I could not find a way to get access to $auth in the `router/index.ts` either.

**Comment by jnt0r** [comment]
Good idea. Just had been a little change :) Just released version 2.2.0 with this feature.

**Comment by upwebdesign** [comment]
@jnt0r I update your package to the latest version today. Exporting the plugin state is a great addition and very useful. Thanks for adding that feature!
