### ISSUE TITLE
Expose $auth with provide() to enable inject() in consumers

### ISSUE THREAD

**Issue by maxweld** [jnt0r/vue-auth0-plugin#220]
**Problem Statement**: app.config.globalProperties are not accessible from within the Composition API's setup() method.

Please consider adding code to "provide" the AuthProperty object so that it can be injected into components. This is considered the preferred method, due to some issues with global properties. 
see [https://forum.vuejs.org/t/how-to-use-globalproperties-in-vue-3-setup-method/108387](https://forum.vuejs.org/t/how-to-use-globalproperties-in-vue-3-setup-method/108387)

I can perform the provide() within my main.ts
```
const app = createApp(App)
app.use(VueAuth0Plugin, auth0Options)
app.provide('auth', app.config.globalProperties.$auth)
app.use(router)
app.mount('#app')
```
But it would be far more elegant if this was performed within the plugin

Then all that is needed to access the object within any component or view is
`const auth = inject('auth') as AuthProperty`

Both **provide** and **inject** can be imported from 'vue'.
The globalProperties can be left in place for backward compatibility, but could perhaps be deprecated for Vue 3.

**Comment by jnt0r** [comment]
Added this feature. Could you try it out and give feedback, please?
