### ISSUE TITLE
New vue-auth0 package

### ISSUE THREAD

**Issue by IlCallo** [jnt0r/vue-auth0-plugin#335]
Hi there, I [just open-sourced a package](https://github.com/dreamonkey/vue-auth0) similar to this one, but with some additional helpers
Just informing you as I saw you released this package more or less when I created mine, and you're currently the first result on Google when searching for vue-auth0 wrapper

Have a nice day!

**Comment by jnt0r** [comment]
Hey @IlCallo, thanks for mentioning this. I will take a look on your plugin in the next days.
