### ISSUE TITLE
Client undefined on first page load

### ISSUE THREAD

**Issue by larsschellhas** [jnt0r/vue-auth0-plugin#381]
Hey,
I'm having an issue with routing on a page refresh because the client in AuthenticationProperties seems to be undefined and therefore, the authentication status is not correctly retrieved. Here is the error:
![image](https://user-images.githubusercontent.com/14281234/154160361-d38325c6-e168-438e-b738-0b62cc7e6ce5.png)

After a few seconds, authentication is established and if I now click on any router-link within my vue app, it just works fine.

**Comment by larsschellhas** [comment]
I've developed a workaround by checking if client is defined within my AuthenticationGuard:

```JS
// If the Auth0Plugin has loaded already, check the authentication state
  if (AuthenticationProperties.client && !AuthenticationState.loading) {
    return guardAction()
  }

  watch(AuthenticationState, async () => {
    if (AuthenticationProperties.client && !AuthenticationState.loading) {
      console.log(AuthenticationState)
      guardAction()
    }
  })
```

**Comment by jnt0r** [comment]
Hey @larsschellhas, did you try the beta version yet?

**Comment by larsschellhas** [comment]
@jnt0r I haven't had the chance to try it, yet. Hopefully on the weekend! But thank you for providing a potential fix! 😊

**Comment by larsschellhas** [comment]
To be honest, @jnt0r, I can't really get it to work right now with the beta version and the promise.
I'm gonna keep my workaround for now as it actually works quite stable :)
But thank you for your efforts!

**Comment by jnt0r** [comment]
Would be happy to make it work for you too.
