### ISSUE TITLE
Should AuthenticationState.error include external errors? 

### ISSUE THREAD

**Issue by rimutaka** [jnt0r/vue-auth0-plugin#418]
I am using `auth.loginWithRedirect();` to log in users with LinkedIn. If a user decides to press CANCEL on the LinkedIn login page the callback URL contains all the details about it like this:

```
http://localhost:3000/?error=access_denied&error_description=The%20user%20cancelled%20LinkedIn%20login&state=...
```

Are we supposed to get those error details from [AuthenticationError](https://auth0.github.io/auth0-spa-js/classes/authenticationerror.html) of _auth0-spa-js_, or `AuthenticationState.error` of the plugin?

**Comment by jnt0r** [comment]
Hey @rimutaka, sorry for replying that late. I just took a look at the error property, and it seems that it is present in the plugin but not propagated by the AuthenticationState. I will take a closer look at this and probably fix that.

**Comment by jnt0r** [comment]
Hey @rimutaka, today I took time to redo some stuff in the plugin and also fixed that the authentication errors were not propagated. I'm preparing a beta release that the features can be tested. I notify you if the version is released.

**Comment by jnt0r** [comment]
Hey @rimutaka, did you try out the [v2.6.2-beta.1](https://github.com/jnt0r/vue-auth0-plugin/releases/tag/v2.6.2-beta.1)? Did it solve your problem?

**Comment by rimutaka** [comment]
@jnt0r , Jonathan, sorry, no, but it's in my TODO list and I will get to it sooner than later. I'm just stuck on other jobs at the moment. Tanks again for fixing it so quickly!
