### ISSUE TITLE
How to get JWT not just Opaque Access Token?

### ISSUE THREAD

**Issue by riodw** [jnt0r/vue-auth0-plugin#620]
Hi there! 
Huge fan on this project so far! Your documentation throughout is filled with clean and well commented code. Love it.

Question for you, when using:
```
const token = await auth.getTokenSilently();
```
which returns:
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9raW5kZXJlZC51cy5hdXRoMC5jb20vIn0..vd32pBiczq_huWmr.oNDQuWNkSMA1vs5LBB4KoaGqu1VF5wN3nUcoPiw4zUvLJklXmwAdq1P1ZQGXVo7NlWuuMPj51XK4095BtQrtIyL4N1QTPbt637bhMZQp-K_eCZGBJQSPfXW6DPPt9dHa1ASqkecAlZBxExxgpgh8eEpksfhdyaDyJ_q2njeAt7IFCpDgY4-nJgyS-XdKVvLQP58zU-Y_qDLfcC7ci1JNERbzcIhjKRiu40lfm5b28d73pT9VFnmxNXlhZo1exVdFbJ-uE1OU0MqchjEt6KKGEhDbtqJs_Dmiekqk7H6jUKh4UO2r_Mm591JmOCTZhig.wcc7nmwLH3nIfMitg64YWA
```

^ This is an **Opaque Access Token**. _(just an example for security reasons)._

I would like access to the **JSON JWT.**

#### Is there a way to do that? Is this a Auth0 thing I need to configure? 

_Thank you so much for any help ❤️ (i may have a few follow-up questions)._

**Comment by jnt0r** [comment]
Hi @riodw, thanks for your Ticket and welcome.
The methods like getTokenSilently get simply delegated to the same method in auth0-spa-js. So probably it's a configuration thing.
Did you take a look at the documentation? https://auth0.com/docs/libraries/auth0-single-page-app-sdk#get-access-token-with-no-interaction
Do you set 'useRefreshToken' to true?

**Comment by jnt0r** [comment]
Hey @riodw, did it solve your problem?

**Comment by riodw** [comment]
Yes I confirmed it's a setting in Auth0 🙂
