### ISSUE TITLE
Invalid type annotations

### ISSUE THREAD

**Issue by gfringeli** [jnt0r/vue-auth0-plugin#778]
The current type annotation of `AuthProperty`s `getTokenSilently` method is incorrect. The return type should be `Promise<undefined | string | GetTokenSilentlyVerboseResponse>` as defined in [auth0/auth0-spa-js](https://github.com/auth0/auth0-spa-js/blob/8e6cd5d2d184ab54856264564630274180f8e39e/src/Auth0Client.ts#L640). Specifically, we have Promise<GetTokenSilentlyVerboseResponse> if the method is called with `detailedResponse: true`.

**Comment by jnt0r** [comment]
Hi @gfringeli, thanks for mentioning this and also providing a pr already. Happy to check and merge.
