### ISSUE TITLE
QueryParams get lost when using vue-router

### ISSUE THREAD

**Issue by jnt0r** [jnt0r/vue-auth0-plugin#790]
When using vue-router the query params present when redirecting to auth0 get lost when redirected back to the application.
This is caused by misunderstanding vue-router push method. Query params passed as part of the path param are not preserved.

**Comment by jnt0r** [comment]
@artur-oliva will post progress on this issue here.

**Comment by artur-oliva** [comment]
Thank you for looking into it!

> @artur-oliva will post progress on this issue here.

**Comment by jnt0r** [comment]
Did version 3.0.13 fix your issue @artur-oliva ?
