### ISSUE TITLE
Issue using querystring ?code= on any route

### ISSUE THREAD

**Issue by lucaghersi** [jnt0r/vue-auth0-plugin#874]
Due to the following piece of code:

```
// If the user is returning to the app after authentication
    if (window.location.search.includes('state=') || window.location.search.includes('code=')) {
// something else
```

you cannot use the code= querystring anywhere in the app.
Unfortunately, my app handles multiple authentication not just the one with Auth0.

Is there a way to make it more restrictive and handle only the redirect_uri of Auth0?

**Comment by jnt0r** [comment]
I think it should be possible to also check that the current uri equals the redirect_uri in this if statement.
Feel free to create a PR for this. Otherwise, I will take a look into this within the next few days.

**Comment by jnt0r** [comment]
Can you take a look at my implementation and tell me your opinion?

**Comment by lucaghersi** [comment]
LGTM!
